export const MAIN_DATA_REQUEST = "MAIN_DATA_REQUEST"
export const MAIN_DATA_SUCCESS = "MAIN_DATA_SUCCESS"
export const MAIN_DATA_ERROR = "MAIN_DATA_ERROR"
export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO"

export const EDIT_TIME_REQUEST = "EDIT_TIME_REQUEST"
export const UPDATE_TIME_SUCCESS = "UPDATE_TIME_SUCCESS"
export const REMOVE_TIME_SUCCESS = "REMOVE_TIME_SUCCESS"
export const EDIT_TIME_ERROR = "EDIT_TIME_ERROR"

export const WHITELIST_DATA_REQUEST = "WHITELIST_DATA_REQUEST"
export const WHITELIST_DATA_SUCCESS = "WHITELIST_DATA_SUCCESS"
export const WHITELIST_DATA_ERROR = "WHITELIST_DATA_ERROR"

export const WHITELIST_REQUEST = "WHITELIST_REQUEST"
export const WHITELIST_ADD_SUCCESS = "WHITELIST_ADD_SUCCESS"
export const WHITELIST_REMOVE_SUCCESS = "WHITELIST_REMOVE_SUCCESS"
export const WHITELIST_ERROR = "WHITELIST_ERROR"

export const FRIENDS_REQUEST = "FRIENDS_REQUEST"
export const FRIENDS_SUCCESS = "FRIENDS_SUCCESS"
export const FRIENDS_ERROR = "FRIENDS_ERROR"
